# Site settings
title: "HYH · Projects & Blog"
email: dbgks25@uos.ac.kr
description: >-
  개인 포트폴리오 및 기술 블로그. 데이터 분석, 웹 개발, 연구 프로젝트를 다룹니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dbgks25.github.io" # the base hostname & protocol for your site
twitter_username: dbgks25
github_username: dbgks25

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugins (GitHub Pages compatible only)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# GitHub Pages doesn't support jekyll-paginate-v2 or autopages
# Using simple tag collection approach instead

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "dbgks25"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: "dbgks25"

# Site navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/about/"

# SEO and social
author:
  name: "dbgks25"
  email: "dbgks25@uos.ac.kr"
  twitter: ""

social:
  name: "dbgks25"
  links:
    - "https://github.com/dbgks25"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CHANGELOG.md
